### ISSUE TITLE
Enhancement: Step animations through custom easings

### ISSUE THREAD

**Issue by ocombe** [julianshapiro/velocity#108]
Hi,

I wanted to animate a background image (sprite sheet) to replace a css3 animation. The current CSS equivalent is:

``` css
@keyframes play {
  from { background-position:    0px; }
  to { background-position: -600px; }
}

.loader {
    width: 20px;
    height: 20px;
    background-image: url("../img/loader.png");
    @include animation(play 1s steps(10) infinite);
}
```

My current implementation with velocity is:

``` js
window.setInterval(function() {
    $element.velocity({
        'background-position-x': ['-600px', '0px']
    }, {
        duration: 1000
    });
}, 1000);
```

But it animates the background position with a step that I can't control. I would like to increment it by 20px each frame (the width of the loader), otherwhise it won't work as expected.

Is this possible with velocity ? Maybe with the easing function ?
