### ISSUE TITLE
Svg uneven dash patterns: are they supported?

### ISSUE THREAD

**Issue by ghost** [julianshapiro/velocity#171]
Hello! Is there any way to get Velocity to set uneven strokeDasharray patterns or is it currently unsupported? :p

**Comment by nmann4789** [comment]
It looks like Velocity is only accepting the first value set on strokeDasharray.  It would be incredibly helpful if this could be added. Setting uneven dash arrays in velocity would allow us to replace the following css animation:

.st0{
  stroke-dashoffset: 10;
  animation: growSmall 1s linear forwards;
}
@keyframes growSmall {
  from {
    stroke-dasharray: 1, 39;
  }
  to {
    stroke-dasharray: 40, 0;
  }
}

**Comment by martinjuhasz** [comment]
I could also really use this feature.
I would like to replace the following CSS-keyframe-Animation with velocity:

```css
@keyframes dash {
  0%{
    stroke-dasharray: 1,200;
    stroke-dashoffset: 0;
  }
  50%{
    stroke-dasharray: 89,200;
    stroke-dashoffset: -35;
  }
  100%{
    stroke-dasharray: 89,200;
    stroke-dashoffset: -124;
  }
}
```

It's an animated loading Button ([Preview on Codepen](http://codepen.io/martinjuhasz/pen/PbyXYv))
