### ISSUE TITLE
Display: 'flex' doesn't provide all prefixing needed

### ISSUE THREAD

**Issue by kpeatt** [julianshapiro/velocity#273]
Just noticed you don't like PRs. Flexbox is one of those weird ones where the syntax changed mid-specification. The current implementation of the flexbox prefixer in Velocity only creates the following prefixes:

``` css
.class {
    display: -ms-flex;         /* This isn't the right setting for IE */
    display: -webkit-flex;     /* NEW - iOS7+ */
    display: flex;             /* Chrome */
}
```

I would expect that it provide all supported values:

``` css
.class {
    display: -webkit-box;      /* OLD - iOS 6-, Safari 3.1-6 */
    display: -moz-box;         /* OLD - Firefox 19  */
    display: -ms-flexbox;      /* TWEENER - IE 10 */
    display: -webkit-flex;     /* NEW - iOS7+ */
    display: flex;             /* Chrome */
}
```

Ideally, providing `display: 'flex'` should generate all of these values for full browser support.
