### ISSUE TITLE
Info: CodePen on Mobile Safari w/ iFrame

### ISSUE THREAD

**Issue by jarrodpayne** [julianshapiro/velocity#69]
I'm just trying out the velocity.js lib for the first time. I am excited to see a valid jQuery animate replacement.

I'm was able to quickly throw up a demo, but the translateX property is janky on iOS.

Here's some javascript from [codepen](http://cdpn.io/qHosw) I am trying out. Any reason it's so janky on mobile? [Here's a link](http://codepen.io/jpdesigndev/full/qHosw/) to the full page you can view on your mobile phone.

I also tried to force hardware acceleration.

``` css
.page {
  -webkit-transform: translate3d(0, 0, 0);
  -webkit-backface-visibility: hidden;
  -webkit-perspective: 1000;
}
```
